name: Refresh Post
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execution
        run: |
          python app.py
          git config --global user.name 'insta-bot'
          git config --global user.email 'bot@github.com'
          git add data.json
          git commit -m "update" || exit 0
          git push
